name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        pip install -e ".[dev]"
        
    - name: Run tests
      run: |
        pytest tests/
        
    - name: Check formatting and imports
      run: |
        ruff format --check .
        ruff check .
        
    - name: Build package
      run: |
        pip install build
        python -m build
        
    - name: Check package
      run: |
        pip install twine
        twine check dist/*
